---
- name: install ntp
  apt: name=ntp state=present
  tags: ntp

- name: configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: start ntp
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: configure dns NS
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  tags: dns
