---
- name : Install apache2
  apt: name={{ item }} state=present
  with_items:
          - apache2
          - git

- name : static contents copy 
  copy: src=index.html dest=/var/www/html/index.html
  tags: web
  notify: restart apache2

- name: service apache2
  service: name=apache2 state=started enabled=yes

